# This is a basic workflow to help you get started with Actions

name: CI - Pull Request

# Controls when the action will run. Triggers the workflow on pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache for Maven
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B verify --file pom.xml

      - name: Publish test report as GitHub annotations
        uses: ashley-taylor/junit-report-annotations-action@v1.0
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: project-g-api.jar
          path: ./target/*.jar
